# =============================================================
# 애플리케이션 설정 파일
# =============================================================

server:
  port: 8081

spring:
  main:
    banner-mode: console
  profiles:
    active:
    - ${SPRING_PROFILES_ACTIVE:dev}
  application:
    name: portfolio_project
    
kakao:
  client-id: ${KAKAO_REST_API_KEY}
  redirect-uri: ${KAKAO_REDIRECT_URI}
  token-url: https://kauth.kakao.com/oauth/token
  user-info-url: https://kapi.kakao.com/v1/user/me
