# =============================================================
# 애플리케이션 설정 파일
# =============================================================

server:
  port: 8081

spring:
  profiles:
    active:
    - dev
  application:
    name: portfolio_project