spring:
    main:
        banner-mode: console
    config:
        import: optional:file:src/.env[.properties]
    mail:
        host: ${MAIL_HOST}
        port: ${MAIL_PORT}
        username: ${MAIL_USERNAME}
        password: ${MAIL_PASSWORD}
        properties:
          mail:
            smtp:
              auth: true
              starttls:
                enable: true
                required: true
    datasource:
        url: ${DB_URL_PROD}
        username: ${DB_USERNAME_PROD}
        password: ${DB_PASSWORD_PROD}
        driver-class-name: ${DB_DRIVER_PROD}
        hikari:
          initialization-fail-timeout: 0
          connection-timeout: 30000
    jpa:
        hibernate:
          ddl-auto: update
        show-sql: true
        properties:
          hibernate:
            "[format_sql]": true
    data:
        redis:
          host: ${REDIS_HOST_PROD}
          port: ${REDIS_PORT_PROD}

cors:
    allowed-origin: ${CORS_ALLOWED_ORIGIN_DEV}

jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION}
    refresh-expiration: ${JWT_REFRESH_EXPIRATION}